language: ruby
sudo: false
cache: bundler
rvm:
  - 1.8.7
  - 1.9.3-p551
  - 2.0.0-p648
  - 2.1.9
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-9.1.15.0
before_install:
  - gem install bundler
matrix:
  allow_failures:
    - rvm: 1.8.7
